"""empty message

Revision ID: 252a4329d989
Revises: fd342e4df95f
Create Date: 2021-01-03 12:25:43.886442

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '252a4329d989'
down_revision = 'fd342e4df95f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('card',
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('card_number', sa.String(length=16), nullable=False),
    sa.Column('card_expiration', sa.String(length=4), nullable=False),
    sa.Column('cvc_code', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('card_number')
    )
    op.create_table('vechicle',
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('registration_plate', sa.String(length=10), autoincrement=False, nullable=False),
    sa.Column('manufacturer', sa.String(length=64), nullable=False),
    sa.Column('model', sa.String(length=64), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('registration_plate')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('vechicle')
    op.drop_table('card')
    # ### end Alembic commands ###
