"""empty message

Revision ID: eabaab3a8a28
Revises: f92228596bd2
Create Date: 2021-01-19 13:13:19.653391

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'eabaab3a8a28'
down_revision = 'f92228596bd2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('bill',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('period_start_date', sa.String(length=30), nullable=False),
    sa.Column('period_end_date', sa.String(length=30), nullable=False),
    sa.Column('total_cost', sa.Float(), nullable=True),
    sa.Column('is_paid', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('bill')
    # ### end Alembic commands ###
